In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [9]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [19]:
X = df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach','exang', 'oldpeak', 'slope', 'ca', 'thal']]
y = df['target']
X,y

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 0     63    1   3       145   233    1        0      150      0      2.3   
 1     37    1   2       130   250    0        1      187      0      3.5   
 2     41    0   1       130   204    0        0      172      0      1.4   
 3     56    1   1       120   236    0        1      178      0      0.8   
 4     57    0   0       120   354    0        1      163      1      0.6   
 ..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
 298   57    0   0       140   241    0        1      123      1      0.2   
 299   45    1   3       110   264    0        1      132      0      1.2   
 300   68    1   0       144   193    1        1      141      0      3.4   
 301   57    1   0       130   131    0        1      115      1      1.2   
 302   57    0   1       130   236    0        0      174      0      0.0   
 
      slope  ca  thal  
 0        0   0     1  
 1        0   0     2  
 2

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
188   50    1   2       140   233    0        1      163      0      0.6   
71    51    1   2        94   227    0        1      154      1      0.0   
106   69    1   3       160   234    1        0      131      0      0.1   
270   46    1   0       120   249    0        0      144      0      0.8   
102   63    0   1       140   195    0        1      179      0      0.0   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3  
..     ...  ..   ...  
188      1   1     3  
71       2   1     3  
106      1   1     2  
270      2   0     3  
102      2   2     2  

[242 rows x 13 columns]

In [27]:
y_train

132    1
202    0
196    0
75     1
176    0
      ..
188    0
71     1
106    1
270    0
102    1
Name: target, Length: 242, dtype: int64

# Using SVC

In [32]:
svc = SVC()
svc.fit(X_train,y_train)
svc_pred_train = svc.predict(X_train)
svc_pred_test = svc.predict(X_test)

In [36]:
print(confusion_matrix(y_train,svc_pred_train))
print()
print(confusion_matrix(y_test,svc_pred_test))

[[ 45  64]
 [ 19 114]]

[[15 14]
 [ 4 28]]


In [38]:
print(accuracy_score(y_train,svc_pred_train))
print(accuracy_score(y_test,svc_pred_test))

0.6570247933884298
0.7049180327868853


# Using Logistic Regression

In [41]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr_pred_train = lr.predict(X_train)
lr_pred_test = lr.predict(X_test)

In [43]:
print(confusion_matrix(y_train,lr_pred_train))
print()
print(confusion_matrix(y_test,lr_pred_test))

[[ 86  23]
 [ 10 123]]

[[25  4]
 [ 3 29]]


In [45]:
print(accuracy_score(y_train,lr_pred_train))
print(accuracy_score(y_test,lr_pred_test))

0.8636363636363636
0.8852459016393442


# Random Forest

In [47]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred_train = rf.predict(X_train)
rf_pred_test = rf.predict(X_test)

In [50]:
print(confusion_matrix(y_train,rf_pred_train))
print()
print(confusion_matrix(y_test,rf_pred_test))

[[109   0]
 [  0 133]]

[[24  5]
 [ 4 28]]


In [52]:
print(accuracy_score(y_train,rf_pred_train))
print(accuracy_score(y_test,rf_pred_test))

1.0
0.8524590163934426


# Random Forest using Hyperparameters

In [61]:
parameters = {
    'criterion' : ['gini','entropy', 'log_loss'],
    'splitter' :['best', 'random'],
    'max_depth' :[1,2,3,4,5],
    'max_features' :['auto','sqrt', 'log2']
}
parameters

{'criterion': ['gini', 'entropy', 'log_loss'],
 'splitter': ['best', 'random'],
 'max_depth': [1, 2, 3, 4, 5],
 'max_features': ['auto', 'sqrt', 'log2']}

In [63]:
rf = RandomForestClassifier(max_samples=0.75, random_state=42,max_depth=6)
rf.fit(X_train,y_train)
rf_pred_train = rf.predict(X_train)
rf_pred_test = rf.predict(X_test)

In [65]:
print(confusion_matrix(y_train,rf_pred_train))
print()
print(confusion_matrix(y_test,rf_pred_test))

[[104   5]
 [  3 130]]

[[26  3]
 [ 3 29]]


In [67]:
print(accuracy_score(y_train,rf_pred_train))
print(accuracy_score(y_test,rf_pred_test))

0.9669421487603306
0.9016393442622951


# OOB Score

In [70]:
rf = RandomForestClassifier(oob_score=True, random_state=42)
rf.fit(X_train,y_train)
rf_pred_train = rf.predict(X_train)
rf_pred_test = rf.predict(X_test)

In [72]:
rf.oob_score_

0.8347107438016529

In [74]:
print(accuracy_score(y_train,rf_pred_train))
print(accuracy_score(y_test,rf_pred_test))

1.0
0.8360655737704918
